import Head from "next/head";
import Link from "next/link";

const Home = () => (
  <>
    <Head>
      <title>Morphis Trans</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <h1 className="title">
        Read <Link href="/posts/first-post">this page!</Link>
      </h1>
    </main>
  </>
);

export default Home;
